spring.application.name=GuestHouseBookingSystem

# Server Configuration
server.port=5050

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/guesthouse_db
spring.datasource.username=root
spring.datasource.password=Mohit1890
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
#jwt.secret=8d5b678d715c02feb6c189546f36ceca80e832ce23c01df41785c22f802b62ab
#jwt.expiration=36000000 # 10 hours in milliseconds

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

# application.properties
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#spring.servlet.multipart.location=${java.io.tmpdir}/ghbs-uploads
# Set a reliable temp directory
#spring.servlet.multipart.location=C:/upload_temp

#spring.security.oauth2.client.registration.google.client-id=231260510050-p5lr158albddcovcutss4in9tielil5v.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohitbajaj189@gmail.com
spring.mail.password=mohit
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
